name: Publish

on:
  push:
    branches:
      - dev
env:
  ACTION_TYPE: "publish"
  USERNAME: ${{github.actor }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Checking coverage
      run: python check_coverage.py